# Generated by Django 3.1.2 on 2020-10-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layerfivemodel',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='layerfourmodel',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='layeronemodel',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='layerthreemodel',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='layertwomodel',
            name='serial_no',
        ),
    ]
