# Generated by Django 3.1.2 on 2020-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='ea8237df-01e1-4c46-8b43-6ffa26667b86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='ea8237df-01e1-4c46-8b43-6ffa26667b86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='ea8237df-01e1-4c46-8b43-6ffa26667b86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='ea8237df-01e1-4c46-8b43-6ffa26667b86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='ea8237df-01e1-4c46-8b43-6ffa26667b86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
