# Generated by Django 3.1.2 on 2020-10-09 18:33

from django.db import migrations
import drf_chart_of_account.scripts


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layeronemodel',
            name='serial_no',
            field=drf_chart_of_account.scripts.AutoFieldNonPrimaryKey(default=1, primary_key=True, unique=True, verbose_name='Serial No.'),
            preserve_default=False,
        ),
    ]
