# Generated by Django 3.1.2 on 2020-10-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='623c0882-0031-43d2-a734-7b595d6497ad', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='623c0882-0031-43d2-a734-7b595d6497ad', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='623c0882-0031-43d2-a734-7b595d6497ad', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='623c0882-0031-43d2-a734-7b595d6497ad', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='623c0882-0031-43d2-a734-7b595d6497ad', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
