# Generated by Django 3.1.2 on 2020-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0002_auto_20201015_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfivemodel',
            name='layer_no',
            field=models.IntegerField(default=5, verbose_name='Layer No'),
        ),
        migrations.AddField(
            model_name='layerfourmodel',
            name='layer_no',
            field=models.IntegerField(default=4, verbose_name='Layer No'),
        ),
        migrations.AddField(
            model_name='layeronemodel',
            name='layer_no',
            field=models.IntegerField(default=1, verbose_name='Layer No'),
        ),
        migrations.AddField(
            model_name='layerthreemodel',
            name='layer_no',
            field=models.IntegerField(default=3, verbose_name='Layer No'),
        ),
        migrations.AddField(
            model_name='layertwomodel',
            name='layer_no',
            field=models.IntegerField(default=2, verbose_name='Layer No'),
        ),
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='1ab7e6e2-f236-46ea-96b3-75a71f088d4a', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='1ab7e6e2-f236-46ea-96b3-75a71f088d4a', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='1ab7e6e2-f236-46ea-96b3-75a71f088d4a', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='1ab7e6e2-f236-46ea-96b3-75a71f088d4a', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='1ab7e6e2-f236-46ea-96b3-75a71f088d4a', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
