# Generated by Django 3.1.2 on 2020-10-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0003_auto_20201015_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='40fb64c2-3562-4cb2-b983-abc7f84c8e32', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='40fb64c2-3562-4cb2-b983-abc7f84c8e32', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='40fb64c2-3562-4cb2-b983-abc7f84c8e32', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='40fb64c2-3562-4cb2-b983-abc7f84c8e32', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='40fb64c2-3562-4cb2-b983-abc7f84c8e32', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
