# Generated by Django 2.0.13 on 2020-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0003_auto_20201015_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='2c7f106f-5677-4741-b09c-4dfb7eb98cf3', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='2c7f106f-5677-4741-b09c-4dfb7eb98cf3', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='2c7f106f-5677-4741-b09c-4dfb7eb98cf3', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='2c7f106f-5677-4741-b09c-4dfb7eb98cf3', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='2c7f106f-5677-4741-b09c-4dfb7eb98cf3', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
