# Generated by Django 2.1.15 on 2020-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0004_auto_20201015_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='8fc76ac1-ee95-4da1-af9c-3c5eca6e3703', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='8fc76ac1-ee95-4da1-af9c-3c5eca6e3703', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='8fc76ac1-ee95-4da1-af9c-3c5eca6e3703', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='8fc76ac1-ee95-4da1-af9c-3c5eca6e3703', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='8fc76ac1-ee95-4da1-af9c-3c5eca6e3703', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
