# Generated by Django 3.1.2 on 2020-10-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0004_auto_20201015_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='55daa268-db6d-4b41-92b5-adfcb6830a86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='55daa268-db6d-4b41-92b5-adfcb6830a86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='55daa268-db6d-4b41-92b5-adfcb6830a86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='55daa268-db6d-4b41-92b5-adfcb6830a86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='55daa268-db6d-4b41-92b5-adfcb6830a86', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
