# Generated by Django 3.1.2 on 2020-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0007_auto_20201015_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='9b82b67c-051d-4e06-a2de-a102e6be4790', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='9b82b67c-051d-4e06-a2de-a102e6be4790', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='9b82b67c-051d-4e06-a2de-a102e6be4790', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='9b82b67c-051d-4e06-a2de-a102e6be4790', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='9b82b67c-051d-4e06-a2de-a102e6be4790', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
