# Generated by Django 2.0.13 on 2020-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0008_auto_20201015_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='10d7fad2-a17d-4c21-bb91-dc0bcceebc3c', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='10d7fad2-a17d-4c21-bb91-dc0bcceebc3c', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='10d7fad2-a17d-4c21-bb91-dc0bcceebc3c', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='10d7fad2-a17d-4c21-bb91-dc0bcceebc3c', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='10d7fad2-a17d-4c21-bb91-dc0bcceebc3c', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
