# Generated by Django 3.0.10 on 2020-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0011_auto_20201015_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='30ee4f75-2216-4189-8cfe-671e6f77df0d', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='30ee4f75-2216-4189-8cfe-671e6f77df0d', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='30ee4f75-2216-4189-8cfe-671e6f77df0d', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='30ee4f75-2216-4189-8cfe-671e6f77df0d', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='30ee4f75-2216-4189-8cfe-671e6f77df0d', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
