# Generated by Django 3.1.2 on 2020-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0012_auto_20201015_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='5ef0cd3d-588d-4af8-8479-68be01a204cd', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='5ef0cd3d-588d-4af8-8479-68be01a204cd', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='5ef0cd3d-588d-4af8-8479-68be01a204cd', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='5ef0cd3d-588d-4af8-8479-68be01a204cd', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='5ef0cd3d-588d-4af8-8479-68be01a204cd', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
