# Generated by Django 3.0.10 on 2020-10-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0016_auto_20201015_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='392deb1a-a9dc-40ae-a300-6652a5326a92', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='392deb1a-a9dc-40ae-a300-6652a5326a92', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='392deb1a-a9dc-40ae-a300-6652a5326a92', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='392deb1a-a9dc-40ae-a300-6652a5326a92', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='392deb1a-a9dc-40ae-a300-6652a5326a92', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
