# Generated by Django 2.0.13 on 2020-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0018_auto_20201015_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='24729a70-e42b-45dd-9674-d88ddf597495', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='24729a70-e42b-45dd-9674-d88ddf597495', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='24729a70-e42b-45dd-9674-d88ddf597495', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='24729a70-e42b-45dd-9674-d88ddf597495', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='24729a70-e42b-45dd-9674-d88ddf597495', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
