# Generated by Django 2.1.15 on 2020-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0019_auto_20201016_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='fed6b121-dcf3-4e2e-ab96-ebe696ae1f76', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='fed6b121-dcf3-4e2e-ab96-ebe696ae1f76', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='fed6b121-dcf3-4e2e-ab96-ebe696ae1f76', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='fed6b121-dcf3-4e2e-ab96-ebe696ae1f76', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='fed6b121-dcf3-4e2e-ab96-ebe696ae1f76', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
