# Generated by Django 2.0.13 on 2020-10-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0020_auto_20201016_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='ef3ec852-d8b7-4e17-a32c-c4b3407dc673', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='ef3ec852-d8b7-4e17-a32c-c4b3407dc673', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='ef3ec852-d8b7-4e17-a32c-c4b3407dc673', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='ef3ec852-d8b7-4e17-a32c-c4b3407dc673', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='ef3ec852-d8b7-4e17-a32c-c4b3407dc673', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
