# Generated by Django 3.0.10 on 2020-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0023_auto_20201016_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='cfe81df6-0600-4dde-9e34-60f393890b64', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='cfe81df6-0600-4dde-9e34-60f393890b64', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='cfe81df6-0600-4dde-9e34-60f393890b64', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='cfe81df6-0600-4dde-9e34-60f393890b64', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='cfe81df6-0600-4dde-9e34-60f393890b64', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
