# Generated by Django 2.0.13 on 2020-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0025_auto_20201016_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='93f0f8ff-e52a-41bb-bb4f-f7c1af244202', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='93f0f8ff-e52a-41bb-bb4f-f7c1af244202', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='93f0f8ff-e52a-41bb-bb4f-f7c1af244202', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='93f0f8ff-e52a-41bb-bb4f-f7c1af244202', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='93f0f8ff-e52a-41bb-bb4f-f7c1af244202', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
