# Generated by Django 2.2.16 on 2020-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0027_auto_20201016_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='9f0708b5-1678-43a7-8832-28fb9d8c7787', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='9f0708b5-1678-43a7-8832-28fb9d8c7787', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='9f0708b5-1678-43a7-8832-28fb9d8c7787', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='9f0708b5-1678-43a7-8832-28fb9d8c7787', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='9f0708b5-1678-43a7-8832-28fb9d8c7787', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
