# Generated by Django 3.1.2 on 2020-10-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_chart_of_account', '0029_auto_20201016_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layerfivemodel',
            name='ref_no',
            field=models.CharField(default='730bb729-666f-46f0-b859-aabb1aff56c5', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerfourmodel',
            name='ref_no',
            field=models.CharField(default='730bb729-666f-46f0-b859-aabb1aff56c5', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layeronemodel',
            name='ref_no',
            field=models.CharField(default='730bb729-666f-46f0-b859-aabb1aff56c5', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layerthreemodel',
            name='ref_no',
            field=models.CharField(default='730bb729-666f-46f0-b859-aabb1aff56c5', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
        migrations.AlterField(
            model_name='layertwomodel',
            name='ref_no',
            field=models.CharField(default='730bb729-666f-46f0-b859-aabb1aff56c5', max_length=80, unique=True, verbose_name='Reference No.'),
        ),
    ]
